ALTER TABLE call_recordings
  ADD COLUMN IF NOT EXISTS banking_product varchar(80),
  ADD COLUMN IF NOT EXISTS channel_layout varchar(20) NOT NULL DEFAULT 'UNKNOWN',
  ADD COLUMN IF NOT EXISTS customer_channel varchar(10),
  ADD COLUMN IF NOT EXISTS agent_channel varchar(10);

ALTER TABLE call_recordings DROP CONSTRAINT IF EXISTS call_recordings_channel_layout_check;
ALTER TABLE call_recordings ADD CONSTRAINT call_recordings_channel_layout_check
  CHECK (channel_layout IN ('STEREO','MONO','UNKNOWN'));
ALTER TABLE call_recordings DROP CONSTRAINT IF EXISTS call_recordings_customer_channel_check;
ALTER TABLE call_recordings ADD CONSTRAINT call_recordings_customer_channel_check
  CHECK (customer_channel IS NULL OR customer_channel IN ('LEFT','RIGHT'));
ALTER TABLE call_recordings DROP CONSTRAINT IF EXISTS call_recordings_agent_channel_check;
ALTER TABLE call_recordings ADD CONSTRAINT call_recordings_agent_channel_check
  CHECK (agent_channel IS NULL OR agent_channel IN ('LEFT','RIGHT'));

ALTER TABLE call_recordings DROP CONSTRAINT IF EXISTS call_recordings_issue_category_check;
UPDATE call_recordings SET issue_category='OTHER'
WHERE issue_category IS NOT NULL AND issue_category NOT IN (
  'CHEQUEBOOK_REQUEST','CHEQUEBOOK_CHANGE','MONEY_TRANSFER','TRANSFER_FAILED','CARD_PAYMENT',
  'CASH_WITHDRAWAL','ACCOUNT_BALANCE','ACCOUNT_STATEMENT','BENEFICIARY_MANAGEMENT','UPI_PAYMENT',
  'ONLINE_BANKING','ACCOUNT_DETAILS_CHANGE','LOAN_ENQUIRY','INTEREST_AND_CHARGES','FRAUD_OR_SCAM',
  'CARD_LOST_OR_STOLEN','CARD_ACTIVATION','CARD_DECLINED','REFUND_PENDING','OTHER'
);
ALTER TABLE call_recordings ADD CONSTRAINT call_recordings_issue_category_check
  CHECK (issue_category IS NULL OR issue_category IN (
    'CHEQUEBOOK_REQUEST','CHEQUEBOOK_CHANGE','MONEY_TRANSFER','TRANSFER_FAILED','CARD_PAYMENT',
    'CASH_WITHDRAWAL','ACCOUNT_BALANCE','ACCOUNT_STATEMENT','BENEFICIARY_MANAGEMENT','UPI_PAYMENT',
    'ONLINE_BANKING','ACCOUNT_DETAILS_CHANGE','LOAN_ENQUIRY','INTEREST_AND_CHARGES','FRAUD_OR_SCAM',
    'CARD_LOST_OR_STOLEN','CARD_ACTIVATION','CARD_DECLINED','REFUND_PENDING','OTHER'
  ));

ALTER TABLE call_recordings DROP CONSTRAINT IF EXISTS call_recordings_issue_cause_check;
UPDATE call_recordings SET issue_cause='UNKNOWN'
WHERE issue_cause IS NOT NULL AND issue_cause NOT IN (
  'CUSTOMER_REQUEST','INCORRECT_DETAILS','INSUFFICIENT_FUNDS','TRANSFER_LIMIT','BENEFICIARY_NOT_ACTIVE',
  'AUTHENTICATION_FAILED','TRANSACTION_DECLINED','TRANSACTION_PENDING','SERVICE_UNAVAILABLE',
  'CARD_BLOCKED','SUSPECTED_FRAUD','DOCUMENTATION_REQUIRED','ACCOUNT_RESTRICTION',
  'PROCESSING_DELAY','FEE_OR_CHARGE','UNKNOWN'
);
ALTER TABLE call_recordings ADD CONSTRAINT call_recordings_issue_cause_check
  CHECK (issue_cause IS NULL OR issue_cause IN (
    'CUSTOMER_REQUEST','INCORRECT_DETAILS','INSUFFICIENT_FUNDS','TRANSFER_LIMIT','BENEFICIARY_NOT_ACTIVE',
    'AUTHENTICATION_FAILED','TRANSACTION_DECLINED','TRANSACTION_PENDING','SERVICE_UNAVAILABLE',
    'CARD_BLOCKED','SUSPECTED_FRAUD','DOCUMENTATION_REQUIRED','ACCOUNT_RESTRICTION',
    'PROCESSING_DELAY','FEE_OR_CHARGE','UNKNOWN'
  ));

CREATE INDEX IF NOT EXISTS idx_calls_banking_product ON call_recordings(started_at, banking_product);
