-- Singleton row caching the team-wide coaching insight (mirrors the
-- application_settings singleton pattern). Regenerated by the worker when a
-- batch finishes processing, not on every dashboard page load.
CREATE TABLE IF NOT EXISTS team_coaching_insight (
  id smallint PRIMARY KEY DEFAULT 1,
  insight text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT team_coaching_insight_singleton CHECK (id = 1)
);
